theme_name = "Everforest Night"
mode = "dark"

background = "#232a2e"
foreground = "#e6dcc6"
secondary = "#2d353b"
secondary_foreground = "#e6dcc6"
border = "#4f5b58"
accent = "#3a4a47"
accent_foreground = "#e6dcc6"
muted = "#3d4a47"
muted_foreground = "#9da9a0"
input = "#343f44"
primary = "#a7c080"
primary_foreground = "#232a2e"
primary_hover = "#93b06e"
primary_active = "#7f9c5c"
danger = "#e67e80"
danger_foreground = "#232a2e"
popover = "#2d353b"
popover_foreground = "#e6dcc6"
selection = "#3a4a47"
ring = "#a7c080"
list_hover = "#313b40"
list_active = "#3a4a47"
scrollbar_thumb = "#4f5b58"
