theme_name = "Nord Light"
mode = "light"

background = "#eceff4"
foreground = "#2e3440"
secondary = "#e5e9f0"
secondary_foreground = "#2e3440"
border = "#d8dee9"
accent = "#d8dee9"
accent_foreground = "#2e3440"
muted = "#d8dee9"
muted_foreground = "#7b88a1"
input = "#e5e9f0"
primary = "#5e81ac"
primary_foreground = "#eceff4"
primary_hover = "#527396"
primary_active = "#466580"
danger = "#bf616a"
danger_foreground = "#eceff4"
popover = "#e5e9f0"
popover_foreground = "#2e3440"
selection = "#c5cede"
ring = "#5e81ac"
list_hover = "#e5e9f0"
list_active = "#d8dee9"
scrollbar_thumb = "#c2c8d4"
