theme_name = "Nord Light"
mode = "light"

background = "#e3e7ee"
foreground = "#2e3440"
secondary = "#d8dee9"
secondary_foreground = "#2e3440"
border = "#c5cede"
accent = "#c5cede"
accent_foreground = "#2e3440"
muted = "#c5cede"
muted_foreground = "#5d6a85"
input = "#d8dee9"
primary = "#5e81ac"
primary_foreground = "#eceff4"
primary_hover = "#527396"
primary_active = "#466580"
danger = "#bf616a"
danger_foreground = "#eceff4"
popover = "#d8dee9"
popover_foreground = "#2e3440"
selection = "#b0bdd1"
ring = "#5e81ac"
list_hover = "#d8dee9"
list_active = "#c5cede"
scrollbar_thumb = "#a8b0c0"
