theme_name = "Ropy Light"
mode = "light"

background = "#fafbfc"
foreground = "#202631"
secondary = "#f1f3f6"
secondary_foreground = "#202631"
border = "#d7dce4"
accent = "#e6edfb"
accent_foreground = "#263e70"
muted = "#f1f3f6"
muted_foreground = "#606a7b"
input = "#d7dce4"
primary = "#4668bc"
primary_foreground = "#ffffff"
primary_hover = "#3c5caa"
primary_active = "#324e94"
danger = "#bd414b"
danger_foreground = "#ffffff"
popover = "#ffffff"
popover_foreground = "#202631"
selection = "#d4e0fa"
ring = "#4668bc"
list_hover = "#edf0f5"
list_active = "#e6edfb"
scrollbar_thumb = "#b4bdcc"
