theme_name = "Ropy Dark"
mode = "dark"

background = "#2d2d2d"
foreground = "#ffffff"
secondary = "#3d3d3d"
secondary_foreground = "#ffffff"
border = "#4d4d4d"
accent = "#303f59"
accent_foreground = "#e1eaff"
muted = "#3d3d3d"
muted_foreground = "#b2bac7"
input = "#555555"
primary = "#8aa8ff"
primary_foreground = "#182132"
primary_hover = "#9bb5ff"
primary_active = "#7694ed"
danger = "#f08087"
danger_foreground = "#28171b"
popover = "#353535"
popover_foreground = "#ffffff"
selection = "#405780"
ring = "#8aa8ff"
list_hover = "#3d3d3d"
list_active = "#303f59"
scrollbar_thumb = "#555555"
