theme_name = "Ropy Dark"
mode = "dark"

background = "#23262d"
foreground = "#e8ecf3"
secondary = "#2c3039"
secondary_foreground = "#e8ecf3"
border = "#424956"
accent = "#303f59"
accent_foreground = "#e1eaff"
muted = "#2c3039"
muted_foreground = "#b2bac7"
input = "#515c6e"
primary = "#8aa8ff"
primary_foreground = "#182132"
primary_hover = "#9bb5ff"
primary_active = "#7694ed"
danger = "#f08087"
danger_foreground = "#28171b"
popover = "#30353f"
popover_foreground = "#e8ecf3"
selection = "#405780"
ring = "#8aa8ff"
list_hover = "#343a46"
list_active = "#303f59"
scrollbar_thumb = "#626d80"
